#line 2 "iec.lex.c"

#line 4 "iec.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 128
#define YY_END_OF_BUFFER 129
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[486] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  129,  127,    1,    1,  121,  121,  121,  121,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      128,   91,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  103,  102,  127,    1,    0,  121,    0,
      121,    0,    0,    0,    0,   48,    0,   82,    0,    0,
        0,    0,   83,   26,    0,    0,    3,    0,    0,    0,
        0,    0,   73,    0,    0,    0,    0,    0,    0,   33,
       60,   69,    0,    0,    0,    0,    0,    0,    0,    0,

       81,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  109,    0,    0,    0,    0,
       96,   97,   98,    0,  104,   99,  100,    0,  101,   69,
        0,  106,    0,    0,  123,    0,  124,  125,   67,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    4,
        0,    0,   80,    0,    0,   13,    0,    0,    0,   68,
        0,   71,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   27,    0,    0,    0,    0,    0,    0,
        0,   42,    0,    0,    0,    0,   70,    0,   92,   67,
      112,   95,  118,  105,   94,  110,  115,  107,   93,   70,

      123,    0,    0,  126,  124,    0,  125,    0,    0,    7,
        8,   78,    0,    0,   25,   14,    0,   76,    0,    0,
       90,    0,    0,    0,   15,    0,    0,    0,    0,    0,
       20,    0,    0,    0,    0,    0,   12,    0,    0,   58,
       74,   24,    5,   30,    0,   17,    0,    0,    0,    0,
        0,   64,    9,    0,    0,  108,  113,  119,  116,  111,
        0,  122,  126,    0,   32,    0,    0,    0,   10,   75,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    6,
        0,    0,   21,   11,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,   19,   88,   16,    0,

        0,    0,    0,    0,    0,    0,   85,    0,    0,  114,
      120,  117,  122,    0,    0,    0,    0,    0,    0,    0,
        0,   77,    0,    0,    0,    0,    0,    0,    0,   47,
        0,    0,    0,    0,   87,    0,   44,   72,   46,   23,
       34,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   84,    0,    0,    0,
        0,    0,    0,   43,    0,    0,    0,   54,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       22,    0,    0,   49,    0,   79,    0,    0,    0,    0,
        0,    0,   31,    0,   50,    0,    0,    0,   59,    0,

        0,    0,    0,    0,    0,    0,    0,   41,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   86,    0,    0,
       66,    0,    0,    0,    0,    0,    0,   36,    0,    0,
        0,    0,    0,    0,    0,    0,   89,    0,   35,    0,
       45,   65,    0,   63,   62,    0,   40,   38,   37,    0,
        0,    0,    0,    0,   55,    0,    0,   29,    0,    0,
        0,    0,    0,   51,   61,    0,   39,    0,   56,   28,
        0,    0,    0,    2,    0,    0,   52,    0,    0,    0,
        0,   57,    0,   53,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    5,    1,    1,
        1,    1,    6,    1,    6,    7,    1,    8,    9,   10,
       11,   11,   11,   12,   11,   13,   14,    1,    1,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,    1,
        1,    1,    1,    1,   40,    1,   41,    1,   42,    1,

       43,    1,    1,   44,   45,    1,    1,   46,    1,    1,
        1,   47,    1,    1,   48,   49,    1,    1,   50,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    4,    4,    4,
        4,    4,    4,    4,    5,    5,    5,    5,    6,    5,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    7,
        1,    1,    8,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[493] =
    {   0,
        0,    0,   49,   51,    0,    0,   53,   55,    0,    0,
       57,    0,  626,  627,   61,   63,   54,   61,   65,  621,
       59,   41,   67,   77,   71,   73,   51,   75,  595,  594,
       90,  590,   84,   81,  104,  102,  606,  109,  591,  573,
      627,  627,  590,  116,  108,  124,  126,  121,  590,  144,
      116,  127,  140,  130,   82,  587,  163,  174,  611,  181,
      610,  165,  188,  595,  580,  627,  582,  576,  576,  580,
      573,  578,  627,  627,  576,  571,  151,  580,  576,  569,
      572,  580,  627,  564,  569,  577,  566,  576,  143,  627,
      627,  627,  564,  186,  573,  563,  558,  556,  569,  560,

      568,  550,  554,  560,  554,  558,  546,  556,  546,  554,
      542,  543,  540,  541,  532,  627,  553,  552,  176,   93,
      627,  627,  627,  539,  540,  627,  627,  541,  627,  538,
      188,  147,  549,  532,  185,    0,  197,  202,  627,  548,
      536,  542,  541,  197,  540,  524,  525,  204,  516,  627,
      521,  521,  627,  536,  534,  627,  517,  535,  517,  627,
      508,  627,  526,  189,  527,  516,  209,  526,  509,  203,
      517,  513,  521,  627,  520,  519,  509,  502,  507,  511,
      505,  492,  505,  508,  511,  496,  627,  477,  627,  498,
      508,  627,  507,  627,  627,  627,  214,  627,  627,  495,

      213,  516,  249,  481,  225,  227,  258,  263,  481,  627,
      627,  627,  496,  484,  477,  627,  498,  627,  495,  282,
      627,  495,  479,  491,  627,  485,  492,  477,  476,  467,
      627,  491,  470,  481,  471,  481,  627,  473,  483,  627,
      627,  459,  627,  627,  464,  627,  463,  470,  461,  261,
      475,  627,  627,  470,  448,  627,  463,  462,  461,  627,
      312,  448,  447,  446,  627,  464,  469,  468,  627,  627,
      225,  210,  462,  449,  461,  445,  439,  462,  454,  627,
      452,  455,  627,  627,  454,  457,  214,  437,  438,  441,
      440,  448,  445,  431,  435,  627,  627,  627,  627,  446,

      433,  423,  434,  431,  423,  438,  627,  428,  410,  627,
      627,  627,  414,  319,  418,  424,  423,  417,  421,  416,
      419,  627,  417,  217,  413,  414,  411,  419,  412,  627,
      406,  412,  410,  405,  627,  419,  627,  627,  627,  627,
      627,  415,  417,  405,  398,  402,  247,  396,  402,  407,
      378,  394,  391,  406,  404,  402,  627,  404,  399,  400,
      389,  382,  397,  627,  389,  386,  398,  627,  386,  388,
      391,  369,  389,  387,  387,  389,  369,  374,  372,  371,
      627,  357,  384,  627,  358,  627,  374,  362,  363,  379,
      358,  375,  627,  372,  350,  366,  349,  353,  627,  368,

      352,  361,  351,  367,  347,  345,  344,  627,  330,  343,
      342,  354,  351,  358,  338,  339,  336,  627,  353,  340,
      627,  348,  351,  331,  342,  328,  322,  627,  311,  310,
      270,  290,  288,  275,  280,  281,  627,  290,  627,  280,
      627,  627,  265,  627,  627,  288,  627,  627,  627,  260,
      271,  270,  264,  266,  627,  274,  263,  627,  265,  247,
      260,  267,  270,  243,  627,  264,  627,  236,  627,  627,
      230,  239,  227,  627,  225,  220,  627,  212,  179,  131,
      124,  627,   42,  627,  627,  333,  339,  343,  348,  353,
      354,  358

    } ;

static yyconst flex_int16_t yy_def[493] =
    {   0,
      485,    1,    1,    1,  486,  486,    1,    1,  486,  486,
        1,   11,  485,  485,  485,  485,  487,  487,   18,   19,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,   19,  485,
       19,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  488,  489,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      488,  490,  485,  491,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  492,  491,  491,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  492,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,    0,  485,  485,  485,  485,  485,
      485,  485

    } ;

static yyconst flex_int16_t yy_nxt[678] =
    {   0,
       14,   15,   16,   14,   14,   14,   14,   17,   18,   19,
       17,   17,   20,   17,   21,   22,   23,   24,   25,   26,
       14,   14,   27,   14,   14,   28,   29,   30,   31,   32,
       14,   33,   34,   35,   36,   37,   38,   39,   14,   14,
       14,   14,   14,   14,   40,   14,   14,   14,   14,   14,
       14,   41,   14,   41,   14,   41,   14,   41,   14,   42,
       58,   43,   57,   57,   57,   57,  484,   58,   62,   67,
       83,   44,   61,   45,   46,   47,   59,   48,   84,   68,
       49,   69,   50,   51,   52,   53,   64,   79,   54,   55,
       65,   71,   66,   60,   56,   70,   76,   85,   77,   72,

       60,   80,   94,   96,   96,   73,   86,   81,   78,   90,
       74,   87,   82,   75,   97,  132,  133,   91,   98,  104,
      146,   92,  119,   95,  105,   99,  100,  106,  192,  107,
      110,  111,  101,  117,  108,  102,   70,  112,   71,  122,
      483,  113,  103,  118,   88,  129,  120,   65,  131,   66,
      128,   76,   73,   77,  123,   89,  121,   74,  482,   90,
       75,  125,  126,   78,   57,   57,   85,   91,  149,   95,
      161,  130,  137,  137,  198,   86,  162,  127,  170,  150,
       87,  135,  135,  135,  135,  135,  135,  135,   59,   59,
       59,   59,   59,   59,   59,  138,  138,  138,  138,  138,

      164,  191,  164,  202,  205,  205,  230,  481,  143,  207,
      207,  207,  207,  207,  231,  165,  213,  165,  166,  167,
      166,  197,  218,  234,  203,  238,  219,  202,  234,  214,
      259,  202,  205,  205,  205,  205,  206,  239,  320,  318,
      480,  208,  333,  235,  321,  479,  360,  478,  235,  361,
      334,  477,  203,  319,  476,  202,  201,  201,  201,  201,
      201,  201,  201,  475,  206,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  300,  377,  301,  474,  302,
      473,  303,  472,  304,  471,  470,  378,  469,  468,  305,
      467,  466,  465,  464,  306,  463,  462,  208,  271,  461,

      460,  272,  459,  458,  273,  457,  456,  455,  454,  453,
      452,  274,  451,  275,  276,  277,  450,  278,  279,  262,
      262,  262,  262,  262,  262,  262,  313,  313,  313,  313,
      313,  313,  313,   41,   41,   41,   41,   41,   41,   41,
       41,   59,   59,  449,  448,   59,  201,  447,  201,  201,
      201,  204,  204,  204,  262,  446,  262,  263,  263,  263,
      263,  313,  445,  444,  313,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,

      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  359,  358,  357,  356,  355,
      354,  353,  352,  314,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  317,  316,  315,  485,  264,  314,  312,  311,
      310,  309,  308,  307,  299,  298,  297,  296,  295,  294,

      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  270,  269,  268,  267,  266,  265,
      264,  261,  260,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  237,  236,  233,  232,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  217,  216,  215,  212,
      211,  210,  209,  200,  199,  196,  195,  194,  193,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  163,  160,  159,  158,  157,  156,  155,  154,

      153,  152,  151,  148,  147,  146,  145,  144,  143,  142,
      141,  140,  139,  136,  485,  134,  124,  116,  115,  114,
      109,   93,   89,   88,   63,  485,   13,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485
    } ;

static yyconst flex_int16_t yy_chk[678] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    4,    4,    7,    7,    8,    8,   11,   11,
       17,   11,   15,   15,   16,   16,  483,   18,   19,   22,
       27,   11,   18,   11,   11,   11,   19,   11,   27,   22,
       11,   23,   11,   11,   11,   11,   21,   26,   11,   11,
       21,   24,   21,   17,   11,   23,   25,   28,   25,   24,

       18,   26,   33,   34,   55,   24,   28,   26,   25,   31,
       24,   28,   26,   24,   34,   55,   55,   31,   35,   36,
      120,   31,   45,   33,   36,   35,   35,   36,  120,   36,
       38,   38,   35,   44,   36,   35,   45,   38,   46,   48,
      481,   38,   35,   44,   51,   52,   46,   44,   54,   44,
       51,   47,   46,   47,   48,   52,   47,   46,  480,   53,
       46,   50,   50,   47,   57,   57,   50,   53,   77,   54,
       89,   53,   62,   62,  132,   50,   89,   50,  132,   77,
       50,   58,   58,   58,   58,   58,   58,   58,   60,   60,
       60,   60,   60,   60,   60,   63,   63,   63,   63,   63,

       94,  119,  131,  135,  137,  137,  164,  479,  119,  138,
      138,  138,  138,  138,  164,   94,  144,  131,   94,   94,
      131,  131,  148,  167,  135,  170,  148,  135,  197,  144,
      197,  201,  205,  205,  206,  206,  137,  170,  272,  271,
      478,  138,  287,  167,  272,  476,  324,  475,  197,  324,
      287,  473,  201,  271,  472,  201,  203,  203,  203,  203,
      203,  203,  203,  471,  205,  207,  207,  207,  207,  207,
      208,  208,  208,  208,  208,  250,  347,  250,  468,  250,
      466,  250,  464,  250,  463,  462,  347,  461,  460,  250,
      459,  457,  456,  454,  250,  453,  452,  207,  220,  451,

      450,  220,  446,  443,  220,  440,  438,  436,  435,  434,
      433,  220,  432,  220,  220,  220,  431,  220,  220,  261,
      261,  261,  261,  261,  261,  261,  314,  314,  314,  314,
      314,  314,  314,  486,  486,  486,  486,  486,  486,  486,
      486,  487,  487,  430,  429,  487,  488,  427,  488,  488,
      488,  489,  489,  489,  490,  426,  490,  491,  491,  491,
      491,  492,  425,  424,  492,  423,  422,  420,  419,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  407,  406,
      405,  404,  403,  402,  401,  400,  398,  397,  396,  395,
      394,  392,  391,  390,  389,  388,  387,  385,  383,  382,

      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  367,  366,  365,  363,  362,  361,  360,  359,
      358,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      346,  345,  344,  343,  342,  336,  334,  333,  332,  331,
      329,  328,  327,  326,  325,  323,  321,  320,  319,  318,
      317,  316,  315,  313,  309,  308,  306,  305,  304,  303,
      302,  301,  300,  295,  294,  293,  292,  291,  290,  289,
      288,  286,  285,  282,  281,  279,  278,  277,  276,  275,
      274,  273,  268,  267,  266,  264,  263,  262,  259,  258,
      257,  255,  254,  251,  249,  248,  247,  245,  242,  239,

      238,  236,  235,  234,  233,  232,  230,  229,  228,  227,
      226,  224,  223,  222,  219,  217,  215,  214,  213,  209,
      204,  202,  200,  193,  191,  190,  188,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  173,
      172,  171,  169,  168,  166,  165,  163,  161,  159,  158,
      157,  155,  154,  152,  151,  149,  147,  146,  145,  143,
      142,  141,  140,  134,  133,  130,  128,  125,  124,  118,
      117,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   95,   93,   88,   87,   86,   85,   84,   82,   81,

       80,   79,   78,   76,   75,   72,   71,   70,   69,   68,
       67,   65,   64,   61,   59,   56,   49,   43,   40,   39,
       37,   32,   30,   29,   20,   13,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[129] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "iec.l"
/**
 * Flex Options
 */
#line 10 "iec.l"
#include "iec.tab.h"
#define TEST_FLEX
/**
* CONTENT: State Definition
*/





/**
* CONTENT: Pattern Naming
* PURPOSE: To use pattern easily
*/
/* Whitespace */
/* Letters, Digits and Identifiers */
/* Numeric Literals */
#line 817 "iec.lex.c"

#define INITIAL 0
#define header_state 1
#define vardecl_list_state 2
#define vardecl_state 3
#define body_state 4
#define il_state 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 50 "iec.l"

 /**
  * PATTERN: Whitespace
  * ACTIONS: Do nothing to eat any whitespace
  */
#line 1015 "iec.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 486 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 627 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 55 "iec.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 56 "iec.l"

	YY_BREAK
/**
  * PATTERN: Public Keywords
  * ACTIONS: Return the token defined by bison
  */
/* EN & ENO */
case 3:
YY_RULE_SETUP
#line 63 "iec.l"
return EN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "iec.l"
return ENO;
	YY_BREAK
/* TRUE & FALSE */
case 5:
YY_RULE_SETUP
#line 66 "iec.l"
return TRUE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "iec.l"
return FALSE;
	YY_BREAK
/* Elementary Data Types */
case 7:
YY_RULE_SETUP
#line 69 "iec.l"
return BOOL;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 71 "iec.l"
return BYTE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 72 "iec.l"
return WORD;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 73 "iec.l"
return DWORD;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 74 "iec.l"
return LWORD;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "iec.l"
return SINT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "iec.l"
return INT;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "iec.l"
return DINT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "iec.l"
return LINT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 81 "iec.l"
return USINT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "iec.l"
return UINT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "iec.l"
return UDINT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "iec.l"
return ULINT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "iec.l"
return REAL;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "iec.l"
return LREAL;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 89 "iec.l"
return WSTRING;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 90 "iec.l"
return STRING;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 "iec.l"
return TIME;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 "iec.l"
return DATE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 "iec.l"
return DT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 "iec.l"
return TOD;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "iec.l"
return DATE_AND_TIME;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "iec.l"
return TIME_OF_DAY;
	YY_BREAK
/* Derived Data Types */
case 30:
YY_RULE_SETUP
#line 99 "iec.l"
return TYPE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "iec.l"
return END_TYPE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "iec.l"
return ARRAY;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "iec.l"
return OF;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "iec.l"
return STRUCT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "iec.l"
return END_STRUCT;
	YY_BREAK
/* Variables Declaration & Initialization */
case 36:
YY_RULE_SETUP
#line 106 "iec.l"
return VAR_INPUT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 107 "iec.l"
return VAR_OUTPUT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 108 "iec.l"
return VAR_IN_OUT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 109 "iec.l"
return VAR_EXTERNAL;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 110 "iec.l"
return VAR_GLOBAL;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "iec.l"
return VAR_TEMP;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 112 "iec.l"
return VAR;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 113 "iec.l"
return END_VAR;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 114 "iec.l"
return RETAIN;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 115 "iec.l"
return NON_RETAIN;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "iec.l"
return R_EDGE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 117 "iec.l"
return F_EDGE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 118 "iec.l"
return AT;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "iec.l"
return CONSTANT;
	YY_BREAK
/* Functions */
case 50:
YY_RULE_SETUP
#line 121 "iec.l"
return FUNCTION;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 122 "iec.l"
return END_FUNCTION;
	YY_BREAK
/* Function Blocks */
case 52:
YY_RULE_SETUP
#line 124 "iec.l"
return FUNCTION_BLOCK;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "iec.l"
return END_FUNCTION_BLOCK;
	YY_BREAK
/* Programs */
case 54:
YY_RULE_SETUP
#line 127 "iec.l"
return PROGRAM;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 128 "iec.l"
return END_PROGRAM;
	YY_BREAK
/* Configuration Elements */
case 56:
YY_RULE_SETUP
#line 130 "iec.l"
return CONFIGURATION;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 131 "iec.l"
return END_CONFIGURATION;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "iec.l"
return TASK;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "iec.l"
return RESOURCE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "iec.l"
return ON;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "iec.l"
return END_RESOURCE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "iec.l"
return VAR_CONFIG;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 137 "iec.l"
return VAR_ACCESS;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "iec.l"
return WITH;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "iec.l"
return READ_WRITE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "iec.l"
return READ_ONLY;
	YY_BREAK
/* Public Operators */
case 67:
YY_RULE_SETUP
#line 142 "iec.l"
return AND;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 143 "iec.l"
return MOD;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 144 "iec.l"
return OR;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 145 "iec.l"
return XOR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 146 "iec.l"
return NOT;
	YY_BREAK
/* ST Subprogram Control Statements */
case 72:
YY_RULE_SETUP
#line 148 "iec.l"
return RETURN;
	YY_BREAK
/* ST Selection Statements */
case 73:
YY_RULE_SETUP
#line 150 "iec.l"
return IF;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 151 "iec.l"
return THEN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 152 "iec.l"
return ELSIF;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 153 "iec.l"
return ELSE;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 154 "iec.l"
return END_IF;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 156 "iec.l"
return CASE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 157 "iec.l"
return END_CASE;
	YY_BREAK
/* ST Iteration Statements */
case 80:
YY_RULE_SETUP
#line 159 "iec.l"
return FOR;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 160 "iec.l"
return TO;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 161 "iec.l"
return BY;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 162 "iec.l"
return DO;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 163 "iec.l"
return END_FOR;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 165 "iec.l"
return WHILE;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 166 "iec.l"
return END_WHILE;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 168 "iec.l"
return REPEAT;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 169 "iec.l"
return UNTIL;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 170 "iec.l"
return END_REPEAT;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 172 "iec.l"
return EXIT;
	YY_BREAK
/**
  * PATTERN: IL STATE EXCLUSIVE
  * ACTIONS: Return the token defined by bison
  */
/* EOL */
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 179 "iec.l"
return EOL;
	YY_BREAK
/* IL operators clashing with standard functions keywords */

case 92:
YY_RULE_SETUP
#line 182 "iec.l"
return ADD;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 183 "iec.l"
return SUB;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 184 "iec.l"
return MUL;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 185 "iec.l"
return DIV;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 186 "iec.l"
return EQ;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 187 "iec.l"
return GE;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 188 "iec.l"
return GT;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 189 "iec.l"
return LE;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 190 "iec.l"
return LT;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 191 "iec.l"
return NE;
	YY_BREAK

/* IL operators clashing with SFC action qualifiers */

case 102:
YY_RULE_SETUP
#line 195 "iec.l"
return S;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 196 "iec.l"
return R;
	YY_BREAK

/* IL operators have no clashes */

case 104:
YY_RULE_SETUP
#line 200 "iec.l"
return LD;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 201 "iec.l"
return LDN;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 202 "iec.l"
return ST;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 203 "iec.l"
return STN;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 204 "iec.l"
return ANDN;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 205 "iec.l"
return ANDN2;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 206 "iec.l"
return ORN;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 207 "iec.l"
return XORN;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 208 "iec.l"
return CAL;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 209 "iec.l"
return CALC;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 210 "iec.l"
return CALCN;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 211 "iec.l"
return RET;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 212 "iec.l"
return RETC;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 213 "iec.l"
return RETCN;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 214 "iec.l"
return JMP;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 215 "iec.l"
return JMPC;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 216 "iec.l"
return JMPCN;
	YY_BREAK

/**
  * PATTERN: Values
  * ACTIONS: Store the token value(the same string) in yylval.ID;
  *          Return the token defined by bison
  */
/* Numeric Literals */
case 121:
YY_RULE_SETUP
#line 229 "iec.l"
{yylval.ID = strdup(yytext); return integer_token;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 230 "iec.l"
{yylval.ID = strdup(yytext); return real_token;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 231 "iec.l"
{yylval.ID = strdup(yytext); return fixed_point_token;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 232 "iec.l"
{yylval.ID = strdup(yytext); return binary_integer_token;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 233 "iec.l"
{yylval.ID = strdup(yytext); return octal_integer_token;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 234 "iec.l"
{yylval.ID = strdup(yytext); return hex_integer_token;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 239 "iec.l"
{return 0;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 240 "iec.l"
ECHO;
	YY_BREAK
#line 1787 "iec.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(header_state):
case YY_STATE_EOF(vardecl_list_state):
case YY_STATE_EOF(vardecl_state):
case YY_STATE_EOF(body_state):
case YY_STATE_EOF(il_state):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 486 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 486 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 485);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 240 "iec.l"


#ifdef TEST_FLEX
int main(int argc, char **argv) {
	int token;
	while(token = yylex()) {
		printf("(line %d)token: %d (%s)\n", yylineno, token, yylval.ID);
	}
	return 0;
}
#endif

